server:
  port: 8086


spring:
  datasource:
    #驱动配置
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.12.163.101:3306/treehole?characterEncoding=UTF-8
    username: Woodpecker_2020
    password: Woodpecker_2020
    #连接池配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 6000    //配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 3000
    druid:
      validation-query: select 1 from dual
      test-on-borrow: false
      test-while-idle: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl